kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-db
  namespace: rhoai-model-registries
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
data:
  database-name: {{ .Values.mysql.database | b64enc }}
  database-password: {{ .Values.mysql.password | b64enc }}
  database-user: {{ .Values.mysql.user | b64enc }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
data:
  MYSQL_USER: {{ .Values.mysql.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc }}
  MYSQL_DATABASE: {{ .Values.mysql.database | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.root_password | b64enc }}
type: Opaque